//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm trú.
        /// </summary>
        internal static string AddressTmp {
            get {
                return ResourceManager.GetString("AddressTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp.
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phép năm.
        /// </summary>
        internal static string AnnualLeave {
            get {
                return ResourceManager.GetString("AnnualLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người duyệt.
        /// </summary>
        internal static string ApproveBy {
            get {
                return ResourceManager.GetString("ApproveBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày duyệt.
        /// </summary>
        internal static string ApproveDate {
            get {
                return ResourceManager.GetString("ApproveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương căn bản.
        /// </summary>
        internal static string BaseSalary {
            get {
                return ResourceManager.GetString("BaseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng viên.
        /// </summary>
        internal static string Candidate {
            get {
                return ResourceManager.GetString("Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền mặt.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục hợp đồng.
        /// </summary>
        internal static string CategoryContract {
            get {
                return ResourceManager.GetString("CategoryContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục nhân sự.
        /// </summary>
        internal static string CategoryHR {
            get {
                return ResourceManager.GetString("CategoryHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục lương.
        /// </summary>
        internal static string CategorySalary {
            get {
                return ResourceManager.GetString("CategorySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCCD.
        /// </summary>
        internal static string CCCD {
            get {
                return ResourceManager.GetString("CCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã công ty.
        /// </summary>
        internal static string CompanyCode {
            get {
                return ResourceManager.GetString("CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa dữ liệu ?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string ContentSalary {
            get {
                return ResourceManager.GetString("ContentSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        internal static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hợp đồng.
        /// </summary>
        internal static string ContractCode {
            get {
                return ResourceManager.GetString("ContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn hợp đồng trong tháng.
        /// </summary>
        internal static string ContractExpirationInMonth {
            get {
                return ResourceManager.GetString("ContractExpirationInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn hợp đồng tháng tới.
        /// </summary>
        internal static string ContractExpirationInNextMonth {
            get {
                return ResourceManager.GetString("ContractExpirationInNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi soạn hợp đồng.
        /// </summary>
        internal static string ContractPlace {
            get {
                return ResourceManager.GetString("ContractPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua.
        /// </summary>
        internal static string DateBuy {
            get {
                return ResourceManager.GetString("DateBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        internal static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khen thưởng.
        /// </summary>
        internal static string DateReward {
            get {
                return ResourceManager.GetString("DateReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ký.
        /// </summary>
        internal static string DateSign {
            get {
                return ResourceManager.GetString("DateSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        internal static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào làm.
        /// </summary>
        internal static string DateStartWord {
            get {
                return ResourceManager.GetString("DateStartWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bảo hành.
        /// </summary>
        internal static string DateWarranty {
            get {
                return ResourceManager.GetString("DateWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học vấn.
        /// </summary>
        internal static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bằng cấp.
        /// </summary>
        internal static string DegreeCode {
            get {
                return ResourceManager.GetString("DegreeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bằng cấp.
        /// </summary>
        internal static string DegreeName {
            get {
                return ResourceManager.GetString("DegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bộ phận.
        /// </summary>
        internal static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bộ phận.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện.
        /// </summary>
        internal static string Deputy {
            get {
                return ResourceManager.GetString("Deputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỉ luật.
        /// </summary>
        internal static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số kỉ luật.
        /// </summary>
        internal static string DisciplineNo {
            get {
                return ResourceManager.GetString("DisciplineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại kỉ luật.
        /// </summary>
        internal static string DisciplineType {
            get {
                return ResourceManager.GetString("DisciplineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học vấn &amp; Kinh nghiệm.
        /// </summary>
        internal static string EducationExperience {
            get {
                return ResourceManager.GetString("EducationExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ nhân viên.
        /// </summary>
        internal static string EmployeeCard {
            get {
                return ResourceManager.GetString("EmployeeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        internal static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        internal static string EmployeeInformation {
            get {
                return ResourceManager.GetString("EmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        internal static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu phiếu lương.
        /// </summary>
        internal static string FindSalary {
            get {
                return ResourceManager.GetString("FindSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại ngữ.
        /// </summary>
        internal static string ForeignLanguage {
            get {
                return ResourceManager.GetString("ForeignLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sức khỏe.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHYT.
        /// </summary>
        internal static string HealthInsurance {
            get {
                return ResourceManager.GetString("HealthInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều cao.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kì nghỉ.
        /// </summary>
        internal static string HolidayName {
            get {
                return ResourceManager.GetString("HolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ lễ.
        /// </summary>
        internal static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh viện.
        /// </summary>
        internal static string Hopital {
            get {
                return ResourceManager.GetString("Hopital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc.
        /// </summary>
        internal static string HourEnd {
            get {
                return ResourceManager.GetString("HourEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu.
        /// </summary>
        internal static string HourStart {
            get {
                return ResourceManager.GetString("HourStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRM.
        /// </summary>
        internal static string HRM {
            get {
                return ResourceManager.GetString("HRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ẩn.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Inform {
            get {
                return ResourceManager.GetString("Inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        internal static string InformationContact {
            get {
                return ResourceManager.GetString("InformationContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin công việc.
        /// </summary>
        internal static string InformationWork {
            get {
                return ResourceManager.GetString("InformationWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterWood.
        /// </summary>
        internal static string InterWoodSystem {
            get {
                return ResourceManager.GetString("InterWoodSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        internal static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin công việc.
        /// </summary>
        internal static string JobInformaton {
            get {
                return ResourceManager.GetString("JobInformaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ trưởng.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nghỉ phép.
        /// </summary>
        internal static string LeaveList {
            get {
                return ResourceManager.GetString("LeaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện pháp luật.
        /// </summary>
        internal static string LegalRepresentative {
            get {
                return ResourceManager.GetString("LegalRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đăng nhập.
        /// </summary>
        internal static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng hôn nhân.
        /// </summary>
        internal static string MarialStatus {
            get {
                return ResourceManager.GetString("MarialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu mẫu.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các khoản đóng hàng tháng.
        /// </summary>
        internal static string MonthlyPayments {
            get {
                return ResourceManager.GetString("MonthlyPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hợp đồng.
        /// </summary>
        internal static string NameContract {
            get {
                return ResourceManager.GetString("NameContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dân tộc.
        /// </summary>
        internal static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tịch.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quốc tịch.
        /// </summary>
        internal static string NationalityCode {
            get {
                return ResourceManager.GetString("NationalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quốc tịch.
        /// </summary>
        internal static string NationalityName {
            get {
                return ResourceManager.GetString("NationalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dân tộc.
        /// </summary>
        internal static string NationCode {
            get {
                return ResourceManager.GetString("NationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dân tộc.
        /// </summary>
        internal static string NationName {
            get {
                return ResourceManager.GetString("NationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sổ.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ phép.
        /// </summary>
        internal static string OnLeave {
            get {
                return ResourceManager.GetString("OnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khác.
        /// </summary>
        internal static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thường gọi.
        /// </summary>
        internal static string OtherName {
            get {
                return ResourceManager.GetString("OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng ca.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng ca ngày lễ.
        /// </summary>
        internal static string OvertimeHoliday {
            get {
                return ResourceManager.GetString("OvertimeHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tăng ca chủ nhật.
        /// </summary>
        internal static string OvertimeSunday {
            get {
                return ResourceManager.GetString("OvertimeSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bên tham gia.
        /// </summary>
        internal static string PartiesInvolved {
            get {
                return ResourceManager.GetString("PartiesInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bên.
        /// </summary>
        internal static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string PasswordNew {
            get {
                return ResourceManager.GetString("PasswordNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string PasswordOld {
            get {
                return ResourceManager.GetString("PasswordOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu.
        /// </summary>
        internal static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày trả lương.
        /// </summary>
        internal static string PayDate {
            get {
                return ResourceManager.GetString("PayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức trả lương.
        /// </summary>
        internal static string PayForms {
            get {
                return ResourceManager.GetString("PayForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân ủy quyền quyết toán thay cho.
        /// </summary>
        internal static string PersonalAuthorization {
            get {
                return ResourceManager.GetString("PersonalAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        internal static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi sinh.
        /// </summary>
        internal static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sác &amp; Phúc lợi.
        /// </summary>
        internal static string PolicyAndBenefits {
            get {
                return ResourceManager.GetString("PolicyAndBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức vụ.
        /// </summary>
        internal static string PositionCode {
            get {
                return ResourceManager.GetString("PositionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ .
        /// </summary>
        internal static string PositionDeputy {
            get {
                return ResourceManager.GetString("PositionDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức vụ.
        /// </summary>
        internal static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí làm việc.
        /// </summary>
        internal static string PositionWork {
            get {
                return ResourceManager.GetString("PositionWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cá nhân.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh thành.
        /// </summary>
        internal static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ phép trong ngày.
        /// </summary>
        internal static string QtyLeaveInDay {
            get {
                return ResourceManager.GetString("QtyLeaveInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tháng hợp đồng.
        /// </summary>
        internal static string QtyMonthContract {
            get {
                return ResourceManager.GetString("QtyMonthContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thẻ.
        /// </summary>
        internal static string RegisCard {
            get {
                return ResourceManager.GetString("RegisCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thân.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôn giáo.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề xuất.
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen thưởng.
        /// </summary>
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức khen thưởng.
        /// </summary>
        internal static string RewardForm {
            get {
                return ResourceManager.GetString("RewardForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số khen thưởng.
        /// </summary>
        internal static string RewardNo {
            get {
                return ResourceManager.GetString("RewardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do khen thưởng.
        /// </summary>
        internal static string RewardReason {
            get {
                return ResourceManager.GetString("RewardReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khen thưởng.
        /// </summary>
        internal static string Rewark {
            get {
                return ResourceManager.GetString("Rewark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền quản lý.
        /// </summary>
        internal static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương căn bản.
        /// </summary>
        internal static string SalaryBasic {
            get {
                return ResourceManager.GetString("SalaryBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công thức lương.
        /// </summary>
        internal static string SalaryFormular {
            get {
                return ResourceManager.GetString("SalaryFormular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng lương.
        /// </summary>
        internal static string SalarySheet {
            get {
                return ResourceManager.GetString("SalarySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới bảng lương.
        /// </summary>
        internal static string SalarySheetCreate {
            get {
                return ResourceManager.GetString("SalarySheetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trường.
        /// </summary>
        internal static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp ca làm việc.
        /// </summary>
        internal static string ShiftArrange {
            get {
                return ResourceManager.GetString("ShiftArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hiểm xã hội.
        /// </summary>
        internal static string SocialInsurance {
            get {
                return ResourceManager.GetString("SocialInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên đã xếp ca trong tháng.
        /// </summary>
        internal static string StaffArrangedShiftsInMonth {
            get {
                return ResourceManager.GetString("StaffArrangedShiftsInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn phòng phẩm.
        /// </summary>
        internal static string Stationery {
            get {
                return ResourceManager.GetString("Stationery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhật ký hệ thống.
        /// </summary>
        internal static string SystemLog {
            get {
                return ResourceManager.GetString("SystemLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeKeeperCard.
        /// </summary>
        internal static string TimeKeeperCard {
            get {
                return ResourceManager.GetString("TimeKeeperCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công.
        /// </summary>
        internal static string Timekeeping {
            get {
                return ResourceManager.GetString("Timekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử chấm công.
        /// </summary>
        internal static string TimekeepingHistory {
            get {
                return ResourceManager.GetString("TimekeepingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ chấm công.
        /// </summary>
        internal static string TimekeepingHour {
            get {
                return ResourceManager.GetString("TimekeepingHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chấm công.
        /// </summary>
        internal static string TimekeepingMachine {
            get {
                return ResourceManager.GetString("TimekeepingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên máy chấm công.
        /// </summary>
        internal static string TimekeepingName {
            get {
                return ResourceManager.GetString("TimekeepingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới bảng chấm công.
        /// </summary>
        internal static string TimesheetCreate {
            get {
                return ResourceManager.GetString("TimesheetCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chốt công từ ngày.
        /// </summary>
        internal static string TimesheetFromDate {
            get {
                return ResourceManager.GetString("TimesheetFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng chấm công.
        /// </summary>
        internal static string Timesheets {
            get {
                return ResourceManager.GetString("Timesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chốt công đến ngày.
        /// </summary>
        internal static string TimesheetToDate {
            get {
                return ResourceManager.GetString("TimesheetToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng phụ cấp.
        /// </summary>
        internal static string TotalAllowance {
            get {
                return ResourceManager.GetString("TotalAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh nhật trong tháng.
        /// </summary>
        internal static string TotalBirthdayInMonth {
            get {
                return ResourceManager.GetString("TotalBirthdayInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày vắng không phép.
        /// </summary>
        internal static string TotalDayAbsent {
            get {
                return ResourceManager.GetString("TotalDayAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày vắng có phép.
        /// </summary>
        internal static string TotalDayLeave {
            get {
                return ResourceManager.GetString("TotalDayLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số ngày.
        /// </summary>
        internal static string TotalDays {
            get {
                return ResourceManager.GetString("TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày làm việc.
        /// </summary>
        internal static string TotalDayWork {
            get {
                return ResourceManager.GetString("TotalDayWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng nhân viên.
        /// </summary>
        internal static string TotalEmployee {
            get {
                return ResourceManager.GetString("TotalEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ vắng không phép.
        /// </summary>
        internal static string TotalHourAbsent {
            get {
                return ResourceManager.GetString("TotalHourAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ tăng ca ngày lễ.
        /// </summary>
        internal static string TotalHourHoliday {
            get {
                return ResourceManager.GetString("TotalHourHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ vắng có phép.
        /// </summary>
        internal static string TotalHourLeave {
            get {
                return ResourceManager.GetString("TotalHourLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hour Overtime.
        /// </summary>
        internal static string TotalHourOvertime {
            get {
                return ResourceManager.GetString("TotalHourOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số giờ.
        /// </summary>
        internal static string TotalHours {
            get {
                return ResourceManager.GetString("TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ tăng ca chủ nhật.
        /// </summary>
        internal static string TotalHourSunday {
            get {
                return ResourceManager.GetString("TotalHourSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số giờ làm việc.
        /// </summary>
        internal static string TotalHourWork {
            get {
                return ResourceManager.GetString("TotalHourWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền ngày lễ.
        /// </summary>
        internal static string TotalMoneyHoliday {
            get {
                return ResourceManager.GetString("TotalMoneyHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền tăng ca.
        /// </summary>
        internal static string TotalMoneyOvertime {
            get {
                return ResourceManager.GetString("TotalMoneyOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền chủ nhật.
        /// </summary>
        internal static string TotalMoneySunday {
            get {
                return ResourceManager.GetString("TotalMoneySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền làm việc.
        /// </summary>
        internal static string TotalMoneyWork {
            get {
                return ResourceManager.GetString("TotalMoneyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng lương.
        /// </summary>
        internal static string TotalSalary {
            get {
                return ResourceManager.GetString("TotalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển khoản.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hợp đồng.
        /// </summary>
        internal static string TypeContract {
            get {
                return ResourceManager.GetString("TypeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại hợp đồng.
        /// </summary>
        internal static string TypeContractCode {
            get {
                return ResourceManager.GetString("TypeContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại dữ liệu.
        /// </summary>
        internal static string TypeData {
            get {
                return ResourceManager.GetString("TypeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại nghỉ.
        /// </summary>
        internal static string TypeLeave {
            get {
                return ResourceManager.GetString("TypeLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đăng ký.
        /// </summary>
        internal static string TypeRegis {
            get {
                return ResourceManager.GetString("TypeRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại khen thưởng.
        /// </summary>
        internal static string TypeReward {
            get {
                return ResourceManager.GetString("TypeReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hiểm thất nghiệp.
        /// </summary>
        internal static string UnemploymentInsurance {
            get {
                return ResourceManager.GetString("UnemploymentInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí công đoàn.
        /// </summary>
        internal static string UnionDues {
            get {
                return ResourceManager.GetString("UnionDues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí công đoàn tối đa.
        /// </summary>
        internal static string UnionFeeMaximum {
            get {
                return ResourceManager.GetString("UnionFeeMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cân nặng.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh nghiệm làm việc.
        /// </summary>
        internal static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca làm việc.
        /// </summary>
        internal static string WorkingShift {
            get {
                return ResourceManager.GetString("WorkingShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ca làm việc.
        /// </summary>
        internal static string WorkingShiftName {
            get {
                return ResourceManager.GetString("WorkingShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm việc Sáng.
        /// </summary>
        internal static string WorkingTimeAM {
            get {
                return ResourceManager.GetString("WorkingTimeAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm việc Chiều.
        /// </summary>
        internal static string WorkingTimePM {
            get {
                return ResourceManager.GetString("WorkingTimePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái làm việc.
        /// </summary>
        internal static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
