//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContract
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ContractCode { get; set; }
        public Nullable<int> TypeContractID { get; set; }
        public Nullable<System.DateTime> DateSign { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Allowance { get; set; }
        public string PayForms { get; set; }
        public Nullable<int> PayDate { get; set; }
        public string WorkingTimeAM { get; set; }
        public string WorkingTimePM { get; set; }
        public string ContractPlace { get; set; }
        public string FileContract { get; set; }
        public string Note { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserUpdated { get; set; }
    }
}
