//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscipline
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> DateDiscipline { get; set; }
        public string NoDiscipline { get; set; }
        public Nullable<int> TypeDiscipline { get; set; }
        public string Reason { get; set; }
        public string FileDiscipline { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
