//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int ID { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string FullName { get; set; }
        public string CommonName { get; set; }
        public bool Gender { get; set; }
        public string Images { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<bool> Married { get; set; }
        public string Address { get; set; }
        public string AddressTmp { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CCCD { get; set; }
        public Nullable<System.DateTime> DateCCCD { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> DateStartWord { get; set; }
        public string Health { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> StatusWork { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> NationID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public string ForeignID { get; set; }
        public Nullable<bool> BHXH { get; set; }
        public Nullable<bool> BHYT { get; set; }
        public Nullable<bool> BHTN { get; set; }
        public Nullable<bool> UnionDues { get; set; }
        public string Note { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<int> MaritalID { get; set; }
        public Nullable<bool> Authority { get; set; }
        public string Comment { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserLastUpdated { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string NoBHXH { get; set; }
        public Nullable<System.DateTime> DateBHXH { get; set; }
        public string IssueByBHXH { get; set; }
        public string NoBHYT { get; set; }
        public Nullable<System.DateTime> fromDateBHYT { get; set; }
        public Nullable<System.DateTime> toDateBHYT { get; set; }
        public string ProvinceBHYT { get; set; }
        public string HopitalBHYT { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> LeaderID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
