//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblISalaryFormula
    {
        public int ID { get; set; }
        public Nullable<double> BHYT { get; set; }
        public Nullable<double> BHTN { get; set; }
        public Nullable<double> BHXH { get; set; }
        public Nullable<double> BHXHMax { get; set; }
        public Nullable<double> UnionDues { get; set; }
        public Nullable<double> UnionDuesMax { get; set; }
        public Nullable<double> Overtime { get; set; }
        public Nullable<double> OvertimeSunday { get; set; }
        public Nullable<double> OvertimeHoliday { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserUpdated { get; set; }
    }
}
