//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeave
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TypeLeaveID { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<double> totalHours { get; set; }
        public Nullable<double> totalDay { get; set; }
        public Nullable<bool> ApproveByLeader { get; set; }
        public Nullable<System.DateTime> DateApproveByLeader { get; set; }
        public Nullable<bool> ApproveByManager { get; set; }
        public Nullable<System.DateTime> DateApproveByManager { get; set; }
        public Nullable<bool> ApproveByHR { get; set; }
        public Nullable<System.DateTime> DateApproveByHR { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserUpdated { get; set; }
    }
}
