//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveDetail
    {
        public int ID { get; set; }
        public Nullable<int> LeaveID { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<double> LeaveQtyHours { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserUpdated { get; set; }
    }
}
