//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReward
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> DateReward { get; set; }
        public string NoReward { get; set; }
        public Nullable<int> TypeReward { get; set; }
        public string Reason { get; set; }
        public string RewardForm { get; set; }
        public Nullable<int> Money { get; set; }
        public string FileReward { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
