//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysLog
    {
        public int ID { get; set; }
        public string AccountLogin { get; set; }
        public Nullable<System.DateTime> DateLog { get; set; }
        public Nullable<int> FunctionLog { get; set; }
        public Nullable<int> ActionLog { get; set; }
        public string ObjectLog { get; set; }
    }
}
