//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalarySheetAllowance
    {
        public int ID { get; set; }
        public Nullable<int> SalarySheetID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<double> AllowanceMoney { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
