//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimesheetDetail
    {
        public int ID { get; set; }
        public Nullable<int> TimesheetCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> totalDayWork { get; set; }
        public Nullable<double> totalHourWork { get; set; }
        public Nullable<double> totalHourOvertime { get; set; }
        public Nullable<double> totalHourOvertimeSunday { get; set; }
        public Nullable<double> totalHourOvertimeHoliday { get; set; }
        public Nullable<double> totalDayLeave { get; set; }
        public Nullable<double> totalHourLeave { get; set; }
        public Nullable<double> totalDayAbsent { get; set; }
        public Nullable<double> totalHourAbsent { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UserUpdated { get; set; }
    }
}
